---
title: "Identifying Factors that Influence Customers Defaulting on Loans"
output: html_notebook
---

```{r}

library('readxl')
library('tidyverse')
library('janitor')
library('GGally')
library('fastDummies')
library('ggfortify')
library('mosaic')
library('mosaicData')
library('modelr')
library('readxl')
library("splitstackshape")
library("rpart")
library("rpart.plot")
library("wesanderson")
library("RColorBrewer")
names(wes_palettes)
```


```{r}
library(readr)
lending_club_loans <- read_csv("C:/Users/44792/OneDrive/Desktop/Codeclan 2022/final_project_loan_default_predictor/data/lending_club_loans.csv")
View(lending_club_loans)
```
```{r}
view(lending_club_loans)
lending_club_loans <- clean_names(lending_club_loans)

```

```{r}
loans1 <- lending_club_loans %>%
  select(loan_amnt,term,int_rate,sub_grade,home_ownership,annual_inc,purpose, loan_status,emp_length, dti)
```
```{r}
loans2 <- loans1 %>%
  filter(!is.na(loan_amnt))
loans2

loans3 <- loans2 %>%
  filter(!is.na(annual_inc))
```

```{r}
loansdropped <-loans3 %>%
  filter(loan_status %in% c("Charged Off","Fully Paid"
                    ))
loansdropped %>%
  count(loan_status)
```
```{r}
mycolour <-colorRampPalette(brewer.pal(name="Dark2", n = 8))(14)
loansdropped %>%
  select(loan_status, purpose)%>%
  group_by(loan_status, purpose)%>%
  summarise(total_count = n())%>%
ggplot(aes(x = loan_status, y = total_count, fill = purpose)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  scale_fill_manual(values = mycolour)+
  ylab("Total count") + xlab("Loan Status")
  


```

 
 
 
```{r}
loansdropped %>%
  select(loan_status, term)%>%
  group_by(loan_status, term)%>%
  summarise(total_count = n())%>%
ggplot(aes(x = loan_status, y = total_count, fill = term)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  scale_fill_brewer(palette="Dark2") +
  labs( x= "Status of Loan",
        y= "Number of Loans",
        title = "Lending Club Status of Loan v Term ")
  
```

```{r}
loansdropped %>%
  select(loan_status, home_ownership)%>%
  group_by(loan_status, home_ownership)%>%
  summarise(total_count = n())%>%
ggplot(aes(x = loan_status, y = total_count, fill = home_ownership)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  scale_fill_brewer(palette="Dark2") + 
  ylab("Total count") + xlab("Loan Status")+
  labs( x= "Loan Status",
        y= "Number of Loans",
        title = "Lending Club Status of Loan v Home Status ")
  
```


```{r}
loans_plot <-loansdropped %>%
  select(loan_status, loan_amnt)%>%
group_by(loan_status, loan_amnt)%>%
  summarise(total_count = n ())

ggplot(loans_plot) + 
  aes(x = loan_status, y = total_count, colour = loan_amnt) +
  geom_line(aes(group = loan_status), alpha = 0.25) +
  geom_point(alpha = 0.5) +
  geom_smooth()
```





```{r}
loansdropped %>%
  select(loan_status, home_ownership)%>%
  group_by(loan_status, home_ownership)%>%
  summarise(total_count = n())%>%
ggplot(aes(x = loan_status, y = total_count, fill = home_ownership)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  scale_fill_brewer(palette="Dark2") + 
  ylab("Total count") + xlab("Loan Status")
```








```{r}
loansmodelling <-loansdropped %>%
  mutate(loan_status = recode(loan_status,"Fully Paid" = FALSE, "Charged Off" = TRUE)) 
loansmodelling
```

#furtherwork on factoring the data

```{r}
loansmodelling2 <- loansmodelling %>%
filter(loan_status %in% c(0,1))%>%
  mutate(home_ownership = as.factor(home_ownership),
         term = factor(term, levels = c(0,1), labels = c("36 months", "60 months")))%>%
         select(home_ownership, term, dti, loan_status)%>%
  na.omit()
```



#   Machine Model ~ 2 Decision Tree


```{r}
set.rseed(19)
n_data <- nrow(loansmodelling)
test_index <- sample(1:n_data, size = n_data*0.2)
loan_test  <- slice(loansdropped, test_index)
loan_train <- slice(loansdropped, -test_index)
```

```{r}
loan_test %>%
 janitor::tabyl(loan_status)
```



```{r}
library("splitstackshape")

sets <- stratified(loansmodelling, group = c("loan_status", "loan_amnt", "term", "home_ownership"), bothSets = TRUE, size = 0.2)

loan_test <- sets$SAMP1
loan_train <- sets$SAMP2

nrow(loan_test)
```
```{r}
nrow(loan_train)
```
```{r}
loan_test %>%
  janitor::tabyl(loan_status)
```

```{r}
loan_train %>%
  janitor::tabyl(loan_status)
```

```{r}
loan_test %>%
  janitor::tabyl(loan_status, home_ownership) %>%
  janitor::adorn_percentages()
```


```{r}
loan_train %>%
  janitor::tabyl(loan_status, home_ownership) %>%
  janitor::adorn_percentages()
```

```{r}
loan_test %>%
  janitor::tabyl(loan_status, loan_amnt) %>%
  janitor::adorn_percentages()
```


```{r}
loan_train %>%
  janitor::tabyl(loan_status, loan_amnt) %>%
  janitor::adorn_percentages()
```

```{r}
loan_test %>%
  janitor::tabyl(loan_status, annual_inc) %>%
  janitor::adorn_percentages()
```

```{r}
loan_train %>%
  janitor::tabyl(loan_status, annual_inc) %>%
  janitor::adorn_percentages()
```


```{r}
loan_test %>%
  janitor::tabyl(loan_status, term) %>%
  janitor::adorn_percentages()
```

```{r}
loan_train %>%
janitor::tabyl(loan_status, term) %>%
  janitor::adorn_percentages()  
```

```{r}
loan_train%>%
  glimpse()
```



```{r}
loan_fit <- rpart(formula = loan_status ~  dti+ loan_amnt +log(annual_inc), 
                     data = loan_train)

rpart.plot(loan_fit)

,
           yesno = 2,
           fallen.leaves = TRUE,
           faclen = 6,
           digits = 4)
```


```{r}
loan_fit <- rpart(formula = loan_status ~ dti, 
                     data = loan_train)

rpart.plot(loan_fit,
           yesno = 2,
           fallen.leaves = TRUE,
           faclen = 6,
           digits = 4)
```

            










